/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/systems/{system_id}/nodes/{code}/translations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Translations
         * @description All cross-system mappings for a code in one call.
         */
        get: operations["get_translations_api_v1_systems__system_id__nodes__code__translations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/systems/{system_id}/nodes/{code}/siblings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Siblings
         * @description Other nodes at the same level under the same parent.
         */
        get: operations["get_siblings_api_v1_systems__system_id__nodes__code__siblings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/systems/{system_id}/nodes/{code}/subtree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Subtree
         * @description Aggregate stats for all nodes under a given code.
         */
        get: operations["get_subtree_api_v1_systems__system_id__nodes__code__subtree_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Compare Systems
         * @description Side-by-side top-level sectors for two systems.
         */
        get: operations["compare_systems_api_v1_compare_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get System Diff
         * @description Nodes in system A with no equivalence mapping to system B.
         */
        get: operations["get_system_diff_api_v1_diff_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodes/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Resolve Code
         * @description Find all systems that contain a given code.
         */
        get: operations["resolve_code_api_v1_nodes__code__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/systems/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Systems Stats
         * @description Per-system leaf and total node counts.
         */
        get: operations["get_systems_stats_api_v1_systems_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/systems": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Systems
         * @description List all classification systems, optionally filtered by country, category, name query, or grouped.
         */
        get: operations["list_systems_api_v1_systems_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/systems/{system_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get System Detail
         * @description Get a classification system with its root nodes.
         */
        get: operations["get_system_detail_api_v1_systems__system_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/systems/{system_id}/nodes/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Node Detail
         * @description Get a single classification node.
         */
        get: operations["get_node_detail_api_v1_systems__system_id__nodes__code__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/systems/{system_id}/nodes/{code}/children": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Node Children
         * @description Get direct children of a node.
         */
        get: operations["get_node_children_api_v1_systems__system_id__nodes__code__children_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/systems/{system_id}/nodes/{code}/ancestors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Node Ancestors
         * @description Get the path from root to this node.
         */
        get: operations["get_node_ancestors_api_v1_systems__system_id__nodes__code__ancestors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/systems/{system_id}/nodes/{code}/equivalences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Node Equivalences
         * @description Get cross-system equivalences for a node.
         */
        get: operations["get_node_equivalences_api_v1_systems__system_id__nodes__code__equivalences_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/systems/{system_id}/nodes/{code}/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Taxonomy For Node
         * @description Generate AI-suggested sub-classifications for a node (preview only, no DB write).
         */
        post: operations["generate_taxonomy_for_node_api_v1_systems__system_id__nodes__code__generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/systems/{system_id}/nodes/{code}/generate/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accept Generated Taxonomy
         * @description Persist user-accepted AI-generated nodes to the database.
         */
        post: operations["accept_generated_taxonomy_api_v1_systems__system_id__nodes__code__generate_accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search
         * @description Full-text search across all classification systems.
         *
         *     Per-IP rate guard: 200/hour. Sized for interactive use (a real
         *     user typing tens of queries in a session) but tight enough to deter
         *     bulk scraping a six-figure node table from a single IP. Once
         *     Cloudflare is in front, the page-cache rule on /api/v1/systems*
         *     absorbs most of this; the in-process cap is defense-in-depth for
         *     queries that bypass cache (unique q values).
         */
        get: operations["search_api_v1_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/equivalences/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Crosswalk Stats
         * @description Get counts of equivalence edges per system pair or per edge kind.
         */
        get: operations["crosswalk_stats_api_v1_equivalences_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/systems/{source}/crosswalk/{target}/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Crosswalk Graph
         * @description Get a graph of crosswalk edges between two systems for visualization.
         */
        get: operations["crosswalk_graph_api_v1_systems__source__crosswalk__target__graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/systems/{source}/crosswalk/{target}/sections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Crosswalk Sections
         * @description Get a section-level summary of crosswalk edges between two systems.
         *
         *     Returns top-level groupings with edge counts for progressive drill-down.
         */
        get: operations["crosswalk_sections_api_v1_systems__source__crosswalk__target__sections_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/countries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Countries
         * @description Return countries that have at least one applicable classification system.
         *
         *     Used by the frontend country-filter dropdown. Sorted alphabetically by
         *     country title (from iso_3166_1). Countries whose ISO 3166-1 node has not
         *     been ingested are excluded so the dropdown never shows bare codes.
         */
        get: operations["list_countries_api_v1_countries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/countries/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Countries Stats
         * @description Return per-country taxonomy coverage stats for all countries.
         *
         *     Used by the world map visualization on the home page.
         *     Returns a list of country objects with:
         *     - country_code: ISO 3166-1 alpha-2
         *     - system_count: number of applicable classification systems
         *     - has_official: whether the country has its own official national standard
         *     - sector_strength_count: number of sector strengths from the geo-sector crosswalk
         */
        get: operations["get_countries_stats_api_v1_countries_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/countries/{country_code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Country Profile
         * @description Return taxonomy profile for a country.
         *
         *     Includes:
         *     - Country metadata (from iso_3166_1 if ingested)
         *     - Applicable classification systems ordered by relevance
         *       (official national system, regional bloc system, UN recommended, historical)
         *     - Known sector strengths (from the geo-sector crosswalk)
         *
         *     country_code: ISO 3166-1 alpha-2 code (e.g. DE, PK, MX, ID, US)
         */
        get: operations["get_country_profile_api_v1_countries__country_code__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit/provenance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Audit Provenance
         * @description Aggregate audit report for data trustworthiness review.
         *
         *     Returns provenance tier breakdown, systems missing file hashes,
         *     structural derivation accounting, and skeleton system detection.
         */
        get: operations["audit_provenance_api_v1_audit_provenance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/classify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Classify Business
         * @description Classify a business/product/occupation description against taxonomy systems.
         *
         *     Requires Pro or Enterprise tier.
         */
        post: operations["classify_business_api_v1_classify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/classify/demo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Classify Demo
         * @description Public classify endpoint gated by email only.
         *
         *     Anonymous callers get the 5-system / 3-result anon tier. Callers
         *     with a valid `dev_session` cookie (i.e., they completed the
         *     magic-link sign-in) get the broader 10-system / 5-result tier.
         *     Records the email as a lead either way.
         *
         *     Per-IP rate guard: 20/hour. The cap is well above any legitimate
         *     interactive use (a user trying ~5 prompts in a session) but tight
         *     enough to deter farming, since each call is LLM-backed and each
         *     INSERT into classify_lead is downstream lead-pipeline noise.
         *
         *     Global classify-lead budget: 500/hour, env-tunable via
         *     CLASSIFY_LEAD_BUDGET_PER_HOUR. The per-IP cap above bounds a
         *     single source; this DB-backed counter catches distributed botnets
         *     rotating IPs (each making 1-2 calls, slipping under the per-IP
         *     cap) and acts as a hard ceiling on LLM cost.
         */
        post: operations["classify_demo_api_v1_classify_demo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Contact
         * @description Submit an enterprise inquiry or general contact form.
         *
         *     Delivers the message via the configured webhook. No admin email
         *     is ever exposed to the client.
         *
         *     Per-IP rate guard: 5/hour. Each submission fires a webhook to our
         *     notification destination; without this, a single IP could flood
         *     the operator inbox/Slack channel.
         */
        post: operations["submit_contact_api_v1_contact_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mcp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Mcp Http Info
         * @description Friendly probe response so browsers/GET probes don't 405.
         */
        get: operations["mcp_http_info_mcp_get"];
        put?: never;
        /**
         * Mcp Http Bridge
         * @description Handle one MCP JSON-RPC message over HTTP POST.
         *
         *     Per-IP rate guard: 600/hour. MCP agents legitimately fan out across
         *     many tool calls in a single user task (a Claude session can fire
         *     dozens of search/translate calls back-to-back), so the cap is
         *     deliberately loose. It still bounds a runaway loop or a single IP
         *     using the public bridge as a free LLM-tool harness.
         */
        post: operations["mcp_http_bridge_mcp_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/developers/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Developers Signup
         * @description Idempotent signup. Creates the user + org if new, then emails a
         *     magic link.
         *
         *     Two abuse guards run BEFORE any DB write or email send:
         *       - per-IP cap (default 5/hour) catches a single source spamming
         *         random emails.
         *       - global email-send budget (default 200/hour, env-tunable via
         *         EMAIL_SEND_BUDGET_PER_HOUR) caps the Resend bill even if a
         *         botnet bypasses the per-IP cap.
         */
        post: operations["developers_signup_api_v1_developers_signup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/magic-callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Auth Magic Callback
         * @description Consume the magic-link token and set the dev_session cookie.
         *
         *     Per-IP rate-limited at 30/min: tokens are 256-bit random, so
         *     flooding cannot guess one, but the limit caps DB cycles spent on
         *     failed lookups during a token-spray attack.
         */
        get: operations["auth_magic_callback_api_v1_auth_magic_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/developers/keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Keys */
        get: operations["list_keys_api_v1_developers_keys_get"];
        put?: never;
        /**
         * Create Key
         * @description Mint a new developer API key for the cookie-authenticated user.
         *
         *     Per-IP rate guard: 10/hour. The cookie itself is gated by the
         *     rate-limited magic-link flow, but a compromised cookie or a single
         *     user wedging a key-generation script could mint hundreds of keys
         *     quickly. Real users mint keys infrequently, so 10/hour is comfortable
         *     headroom without leaving a flood vector open.
         *
         *     CSRF: requires the X-CSRF-Token header to match the wot_csrf cookie
         *     set on magic-callback. Blocks same-origin XSS-driven key minting.
         */
        post: operations["create_key_api_v1_developers_keys_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/developers/keys/{key_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke Key
         * @description Revoke an API key the cookie-authenticated user owns.
         *
         *     CSRF: requires the X-CSRF-Token header to match the wot_csrf cookie
         *     set on magic-callback.
         */
        delete: operations["revoke_key_api_v1_developers_keys__key_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Sign the user out by clearing both auth cookies.
         *
         *     Called from the Header user-menu after PR-#155 stripped OAuth + the
         *     legacy /auth/* router. We deliberately do NOT invalidate the JWT
         *     server-side: the dev_session cookie is short-lived (60-min TTL) and
         *     httponly, and sign-out is a one-click client-side action. The
         *     backend just needs to clear both cookies on this domain so the
         *     Header detects the signed-out state via the absence of wot_csrf.
         */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/billing/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Checkout Endpoint */
        post: operations["checkout_endpoint_api_v1_billing_checkout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/billing/portal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Portal Endpoint */
        post: operations["portal_endpoint_api_v1_billing_portal_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/billing/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * State Endpoint
         * @description Return the org's current billing state for the dashboard panel.
         */
        get: operations["state_endpoint_api_v1_billing_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wiki": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Wiki Pages
         * @description List all wiki guide pages.
         */
        get: operations["list_wiki_pages_api_v1_wiki_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wiki/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Wiki Page
         * @description Get a single wiki page by slug.
         */
        get: operations["get_wiki_page_api_v1_wiki__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Return liveness + database reachability in a single round trip.
         *
         *     Response shape:
         *       { "status": "ok" | "degraded", "db": "ok" | "fail", "latency_ms": 0 }
         *
         *     Returns 200 when the pool is reachable and can run SELECT 1,
         *     503 when the database probe fails.
         */
        get: operations["healthz_api_v1_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Version
         * @description Return the app version, git SHA, and build time.
         *
         *     Lets operators verify which image is actually running behind a
         *     load balancer. Values are read from env (APP_VERSION, GIT_SHA,
         *     BUILD_TIME) injected at container build time.
         */
        get: operations["version_api_v1_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/_internal/sentry-test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sentry Test
         * @description Throw a deliberate exception so the operator can verify Sentry
         *     is wired up and receiving events.
         *
         *     Gated three ways:
         *       1. Disabled unless SENTRY_TEST_TOKEN is set in the environment.
         *       2. Caller must present that token via the X-Sentry-Test-Token header.
         *       3. Comparison is constant-time to avoid token-leak via timing.
         *
         *     On a successful auth, raises a fresh exception type so it shows up
         *     cleanly in the Sentry inbox without polluting real error groupings.
         *     Returns the request_id so the operator can correlate the Sentry
         *     event with the access log.
         */
        post: operations["sentry_test_api_v1__internal_sentry_test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/robots.txt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Robots Txt */
        get: operations["robots_txt_robots_txt_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/llms.txt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Llms Txt */
        get: operations["llms_txt_llms_txt_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/llms-full.txt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Llms Full Txt */
        get: operations["llms_full_txt_llms_full_txt_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AcceptTaxonomyRequest */
        AcceptTaxonomyRequest: {
            /** Nodes */
            nodes: components["schemas"]["GeneratedNode"][];
        };
        /** AuditProvenanceResponse */
        AuditProvenanceResponse: {
            /** Total Systems */
            total_systems: number;
            /** Total Nodes */
            total_nodes: number;
            /** Provenance Tiers */
            provenance_tiers: components["schemas"]["ProvenanceTierSummary"][];
            /** Official Missing Hash */
            official_missing_hash: components["schemas"]["SystemResponse"][];
            /** Structural Derivation Count */
            structural_derivation_count: number;
            /** Structural Derivation Nodes */
            structural_derivation_nodes: number;
            /** Skeleton Systems */
            skeleton_systems: components["schemas"]["SystemResponse"][];
        };
        /** BillingStateResponse */
        BillingStateResponse: {
            /**
             * Tier
             * @enum {string}
             */
            tier: "free" | "pro" | "enterprise";
            /** Tier Active Until */
            tier_active_until?: string | null;
            /** Classify Today Count */
            classify_today_count: number;
            /** Has Stripe Customer */
            has_stripe_customer: boolean;
        };
        /** CheckoutRequest */
        CheckoutRequest: {
            /**
             * Plan
             * @enum {string}
             */
            plan: "pro_monthly" | "pro_annual";
        };
        /** CheckoutResponse */
        CheckoutResponse: {
            /** Checkout Url */
            checkout_url: string;
        };
        /** ClassifyDemoRequest */
        ClassifyDemoRequest: {
            /**
             * Email
             * @description Lead email for follow-up
             */
            email: string;
            /**
             * Text
             * @description Business/product/occupation description
             */
            text: string;
            /**
             * Countries
             * @description Optional ISO 3166-1 alpha-2 country codes. When supplied, classify against the systems applicable to those countries (plus globally recommended standards like ISIC Rev 4) instead of the default demo set.
             */
            countries?: string[] | null;
        };
        /** ClassifyDemoResponse */
        ClassifyDemoResponse: {
            /** Query */
            query: string;
            /**
             * Domain Matches
             * @description Matches from curated WoT Domain taxonomies (system_id starts 'domain_').
             */
            domain_matches?: unknown[];
            /**
             * Standard Matches
             * @description Matches from official standard systems (NAICS, ISIC, NACE, SIC, SOC, ...).
             */
            standard_matches?: unknown[];
            /** Disclaimer */
            disclaimer: string;
            /** Report Issue Url */
            report_issue_url: string;
            /**
             * Demo
             * @default true
             */
            demo: boolean;
            /**
             * Is Logged In
             * @description True when the request carried a valid `dev_session` cookie. Logged-in callers get the broader 10-system / 5-result-per-system tier; anonymous callers get the 5-system / 3-result tier.
             * @default false
             */
            is_logged_in: boolean;
            /** Upgrade Cta */
            upgrade_cta: string;
            /**
             * Compound
             * @default false
             */
            compound: boolean;
            /** Atoms */
            atoms?: unknown[] | null;
            /** Hero */
            hero?: {
                [key: string]: unknown;
            } | null;
            /** Cta */
            cta?: {
                [key: string]: unknown;
            } | null;
            /**
             * Llm Used
             * @default false
             */
            llm_used: boolean;
            /**
             * Llm Keywords
             * @default []
             */
            llm_keywords: unknown[];
            /**
             * Scope
             * @description Present only when `countries` was supplied. Mirrors the shape returned by the paid /classify endpoint.
             */
            scope?: {
                [key: string]: unknown;
            } | null;
        };
        /** ClassifyRequest */
        ClassifyRequest: {
            /**
             * Text
             * @description Free-text to classify
             */
            text: string;
            /**
             * Systems
             * @description Optional list of system IDs to search. Default: major systems.
             */
            systems?: string[] | null;
            /**
             * Countries
             * @description Optional ISO 3166-1 alpha-2 country codes. Scopes candidates to systems applicable to these countries plus universal recommended standards (UN/WCO/WHO). Overrides `systems` when set.
             */
            countries?: string[] | null;
            /**
             * Limit
             * @description Max matches per system
             * @default 5
             */
            limit: number;
        };
        /** ClassifyResponse */
        ClassifyResponse: {
            /** Query */
            query: string;
            /**
             * Domain Matches
             * @description Matches from curated WoT Domain taxonomies (plain-language, concrete).
             */
            domain_matches?: components["schemas"]["ClassifySystemMatch"][];
            /**
             * Standard Matches
             * @description Matches from official standard systems (NAICS, ISIC, NACE, SIC, SOC, ...).
             */
            standard_matches?: components["schemas"]["ClassifySystemMatch"][];
            /** Crosswalks */
            crosswalks: components["schemas"]["CrosswalkEdge"][];
            /** Disclaimer */
            disclaimer: string;
            /** Report Issue Url */
            report_issue_url: string;
            /** @description Present only when `countries` was supplied. Shows the resolved country-specific vs global candidate systems the classifier used. */
            scope?: components["schemas"]["ScopeInfo"] | null;
        };
        /** ClassifyResult */
        ClassifyResult: {
            /** Code */
            code: string;
            /** Title */
            title: string;
            /** Score */
            score: number;
            /** Level */
            level: number;
            /**
             * Crosswalk Count
             * @description Number of equivalence edges originating from this code. The UI uses this to hide the 'Show crosswalks' affordance for codes with no outgoing edges.
             * @default 0
             */
            crosswalk_count: number;
        };
        /** ClassifySystemMatch */
        ClassifySystemMatch: {
            /** System Id */
            system_id: string;
            /** System Name */
            system_name: string;
            /**
             * Category
             * @description 'domain' for curated WoT taxonomies (system_id starts 'domain_'), 'standard' otherwise.
             */
            category: string;
            /** Results */
            results: components["schemas"]["ClassifyResult"][];
        };
        /** CompareSectorsResponse */
        CompareSectorsResponse: {
            /** System A */
            system_a: components["schemas"]["NodeResponse"][];
            /** System B */
            system_b: components["schemas"]["NodeResponse"][];
        };
        /** ContactRequest */
        ContactRequest: {
            /**
             * Name
             * @description Contact name
             */
            name: string;
            /**
             * Company
             * @description Company name
             */
            company?: string | null;
            /**
             * Email
             * @description Contact email
             */
            email: string;
            /**
             * Message
             * @description Message
             */
            message: string;
        };
        /** ContactResponse */
        ContactResponse: {
            /**
             * Status
             * @default received
             */
            status: string;
            /**
             * Message
             * @default Thank you for your inquiry. We will be in touch shortly.
             */
            message: string;
        };
        /** CreateKeyRequest */
        CreateKeyRequest: {
            /** Name */
            name: string;
            /** Scopes */
            scopes?: string[];
            /** Expires In Days */
            expires_in_days?: number | null;
        };
        /** CrosswalkEdge */
        CrosswalkEdge: {
            /** From */
            from: string;
            /** To */
            to: string;
            /** Match Type */
            match_type: string;
            /**
             * Edge Kind
             * @description Computed: '{source}_{target}' where each side is 'domain' if the system_id starts with 'domain_', else 'standard'.
             */
            edge_kind: string;
        };
        /** CrosswalkGraphEdge */
        CrosswalkGraphEdge: {
            /** Source */
            source: string;
            /** Target */
            target: string;
            /** Match Type */
            match_type: string;
        };
        /** CrosswalkGraphNode */
        CrosswalkGraphNode: {
            /** Id */
            id: string;
            /** System */
            system: string;
            /** Code */
            code: string;
            /** Title */
            title: string;
        };
        /** CrosswalkGraphResponse */
        CrosswalkGraphResponse: {
            /** Source System */
            source_system: string;
            /** Target System */
            target_system: string;
            /** Nodes */
            nodes: components["schemas"]["CrosswalkGraphNode"][];
            /** Edges */
            edges: components["schemas"]["CrosswalkGraphEdge"][];
            /** Total Edges */
            total_edges: number;
            /** Truncated */
            truncated: boolean;
        };
        /** CrosswalkSection */
        CrosswalkSection: {
            /** Source Section */
            source_section: string;
            /** Source Title */
            source_title: string;
            /** Target Section */
            target_section: string;
            /** Target Title */
            target_title: string;
            /** Edge Count */
            edge_count: number;
            /** Exact Count */
            exact_count: number;
        };
        /** CrosswalkSectionsResponse */
        CrosswalkSectionsResponse: {
            /** Source System */
            source_system: string;
            /** Target System */
            target_system: string;
            /** Sections */
            sections: components["schemas"]["CrosswalkSection"][];
            /** Total Edges */
            total_edges: number;
        };
        /** CrosswalkStatResponse */
        CrosswalkStatResponse: {
            /** Source System */
            source_system: string;
            /** Target System */
            target_system: string;
            /** Edge Count */
            edge_count: number;
            /** Exact Count */
            exact_count: number;
            /** Partial Count */
            partial_count: number;
        };
        /** EdgeKindStatResponse */
        EdgeKindStatResponse: {
            /** Edge Kind */
            edge_kind: string;
            /** Edge Count */
            edge_count: number;
            /**
             * Exact Count
             * @default 0
             */
            exact_count: number;
            /**
             * Partial Count
             * @default 0
             */
            partial_count: number;
            /**
             * Broad Count
             * @default 0
             */
            broad_count: number;
        };
        /** EquivalenceResponse */
        EquivalenceResponse: {
            /** Source System */
            source_system: string;
            /** Source Code */
            source_code: string;
            /** Target System */
            target_system: string;
            /** Target Code */
            target_code: string;
            /** Match Type */
            match_type: string;
            /** Notes */
            notes?: string | null;
            /** Source Title */
            source_title?: string | null;
            /** Target Title */
            target_title?: string | null;
            /**
             * Source Category
             * @description Category of source_system: 'domain' or 'standard'.
             * @default standard
             */
            source_category: string;
            /**
             * Target Category
             * @description Category of target_system: 'domain' or 'standard'.
             * @default standard
             */
            target_category: string;
            /**
             * Edge Kind
             * @description One of: standard_standard, standard_domain, domain_standard, domain_domain.
             * @default standard_standard
             */
            edge_kind: string;
        };
        /** GenerateTaxonomyRequest */
        GenerateTaxonomyRequest: {
            /**
             * Count
             * @default 5
             */
            count: number;
        };
        /** GenerateTaxonomyResponse */
        GenerateTaxonomyResponse: {
            /** Parent System Id */
            parent_system_id: string;
            /** Parent Code */
            parent_code: string;
            /** Nodes */
            nodes: components["schemas"]["GeneratedNode"][];
        };
        /** GeneratedNode */
        GeneratedNode: {
            /** Code */
            code: string;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** Reason */
            reason?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** KeyCreatedResponse */
        KeyCreatedResponse: {
            /** Raw Key */
            raw_key: string;
            metadata: components["schemas"]["KeyMetadata"];
        };
        /** KeyMetadata */
        KeyMetadata: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Key Prefix */
            key_prefix: string;
            /** Scopes */
            scopes: string[];
            /** Created At */
            created_at: string;
            /** Expires At */
            expires_at: string | null;
            /** Last Used At */
            last_used_at: string | null;
            /** Revoked At */
            revoked_at: string | null;
        };
        /** NodeResponse */
        NodeResponse: {
            /** Id */
            id: number;
            /** System Id */
            system_id: string;
            /** Code */
            code: string;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /**
             * Level
             * @default 0
             */
            level: number;
            /** Parent Code */
            parent_code?: string | null;
            /** Sector Code */
            sector_code?: string | null;
            /**
             * Is Leaf
             * @default false
             */
            is_leaf: boolean;
            /**
             * Seq Order
             * @default 0
             */
            seq_order: number;
            /**
             * Category
             * @description 'domain' if system_id starts 'domain_', else 'standard'.
             * @default standard
             */
            category: string;
            /** Data Provenance */
            data_provenance?: string | null;
            /** License */
            license?: string | null;
            /** Source Url */
            source_url?: string | null;
            /** Source Date */
            source_date?: string | null;
            /** Source File Hash */
            source_file_hash?: string | null;
            /** Source Url For Code */
            source_url_for_code?: string | null;
        };
        /** PortalResponse */
        PortalResponse: {
            /** Portal Url */
            portal_url: string;
        };
        /** ProvenanceTierSummary */
        ProvenanceTierSummary: {
            /** Data Provenance */
            data_provenance: string | null;
            /** System Count */
            system_count: number;
            /** Node Count */
            node_count: number;
        };
        /** ScopeInfo */
        ScopeInfo: {
            /** Countries */
            countries: string[];
            /** Country Specific Systems */
            country_specific_systems: string[];
            /** Global Standard Systems */
            global_standard_systems: string[];
            /** Candidate Systems */
            candidate_systems: string[];
        };
        /** SignupRequest */
        SignupRequest: {
            /** Email */
            email: string;
        };
        /** SignupResponse */
        SignupResponse: {
            /** Detail */
            detail: string;
            /** Magic Link Url */
            magic_link_url?: string | null;
        };
        /** SubtreeSummaryResponse */
        SubtreeSummaryResponse: {
            /** System Id */
            system_id: string;
            /** Code */
            code: string;
            /** Title */
            title: string;
            /** Total Nodes */
            total_nodes: number;
            /** Leaf Count */
            leaf_count: number;
            /** Max Depth */
            max_depth: number;
        };
        /** SystemDetailResponse */
        SystemDetailResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Full Name */
            full_name?: string | null;
            /** Region */
            region?: string | null;
            /** Version */
            version?: string | null;
            /** Authority */
            authority?: string | null;
            /** Url */
            url?: string | null;
            /** Tint Color */
            tint_color?: string | null;
            /**
             * Node Count
             * @default 0
             */
            node_count: number;
            /** Source Url */
            source_url?: string | null;
            /** Source Date */
            source_date?: string | null;
            /** Data Provenance */
            data_provenance?: string | null;
            /** License */
            license?: string | null;
            /** Source File Hash */
            source_file_hash?: string | null;
            /**
             * Category
             * @description 'domain' for curated WoT Domain taxonomies (id starts 'domain_'), 'standard' otherwise.
             * @default standard
             */
            category: string;
            /**
             * Roots
             * @default []
             */
            roots: components["schemas"]["NodeResponse"][];
        };
        /** SystemGranularityResponse */
        SystemGranularityResponse: {
            /** System Id */
            system_id: string;
            /** Total Nodes */
            total_nodes: number;
            /** Leaf Nodes */
            leaf_nodes: number;
        };
        /** SystemResponse */
        SystemResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Full Name */
            full_name?: string | null;
            /** Region */
            region?: string | null;
            /** Version */
            version?: string | null;
            /** Authority */
            authority?: string | null;
            /** Url */
            url?: string | null;
            /** Tint Color */
            tint_color?: string | null;
            /**
             * Node Count
             * @default 0
             */
            node_count: number;
            /** Source Url */
            source_url?: string | null;
            /** Source Date */
            source_date?: string | null;
            /** Data Provenance */
            data_provenance?: string | null;
            /** License */
            license?: string | null;
            /** Source File Hash */
            source_file_hash?: string | null;
            /**
             * Category
             * @description 'domain' for curated WoT Domain taxonomies (id starts 'domain_'), 'standard' otherwise.
             * @default standard
             */
            category: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WikiPageDetail */
        WikiPageDetail: {
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Content Markdown */
            content_markdown: string;
        };
        /** WikiPageSummary */
        WikiPageSummary: {
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_translations_api_v1_systems__system_id__nodes__code__translations_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                system_id: string;
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EquivalenceResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_siblings_api_v1_systems__system_id__nodes__code__siblings_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                system_id: string;
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_subtree_api_v1_systems__system_id__nodes__code__subtree_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                system_id: string;
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubtreeSummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_systems_api_v1_compare_get: {
        parameters: {
            query: {
                /** @description First system ID */
                a: string;
                /** @description Second system ID */
                b: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompareSectorsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_system_diff_api_v1_diff_get: {
        parameters: {
            query: {
                /** @description Source system ID */
                a: string;
                /** @description Target system to check coverage against */
                b: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_code_api_v1_nodes__code__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_systems_stats_api_v1_systems_stats_get: {
        parameters: {
            query?: {
                system_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemGranularityResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_systems_api_v1_systems_get: {
        parameters: {
            query?: {
                /** @description Group results (e.g. 'region') */
                group_by?: string | null;
                /** @description Filter by ISO 3166-1 alpha-2 country code (e.g. DE, PK, MX) */
                country?: string | null;
                /** @description Filter by category: 'domain' for curated Domain taxonomies, 'standard' for official standards (NAICS, ISIC, ...), omit for all. */
                category?: string | null;
                /** @description Optional case-insensitive substring filter across id, name, full_name, authority, and region. */
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_system_detail_api_v1_systems__system_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                system_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_node_detail_api_v1_systems__system_id__nodes__code__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                system_id: string;
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_node_children_api_v1_systems__system_id__nodes__code__children_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                system_id: string;
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_node_ancestors_api_v1_systems__system_id__nodes__code__ancestors_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                system_id: string;
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_node_equivalences_api_v1_systems__system_id__nodes__code__equivalences_get: {
        parameters: {
            query?: {
                /** @description Filter by edge kind (comma-separated). One or more of: standard_standard, standard_domain, domain_standard, domain_domain. */
                edge_kind?: string | null;
            };
            header?: never;
            path: {
                system_id: string;
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EquivalenceResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_taxonomy_for_node_api_v1_systems__system_id__nodes__code__generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                system_id: string;
                code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateTaxonomyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateTaxonomyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_generated_taxonomy_api_v1_systems__system_id__nodes__code__generate_accept_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                system_id: string;
                code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptTaxonomyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_v1_search_get: {
        parameters: {
            query: {
                /** @description Search query */
                q: string;
                /** @description Filter by system ID. Pass multiple times to match any of several systems: ?system_id=naics_2022&system_id=isic_rev4. */
                system_id?: string[] | null;
                /** @description Filter by system ID (alias, repeatable). */
                system?: string[] | null;
                /** @description Filter by category: 'domain' or 'standard'. Omit for both. */
                category?: string | null;
                /** @description Optional ISO 3166-1 alpha-2 country codes. Scopes results to systems applicable to these countries plus universal recommended standards (UN/WCO/WHO). Pass multiple times to union: ?countries=US&countries=CA. */
                countries?: string[] | null;
                /** @description Max results */
                limit?: number;
                /** @description Return results grouped by system */
                grouped?: boolean;
                /** @description Include ancestors and children for each match */
                context?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crosswalk_stats_api_v1_equivalences_stats_get: {
        parameters: {
            query?: {
                /** @description Filter to a specific system */
                system_id?: string | null;
                /** @description Grouping dimension. Omit (default) for system-pair stats. Pass 'edge_kind' for counts grouped by the four edge kinds (standard_standard, standard_domain, domain_standard, domain_domain). */
                group_by?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrosswalkStatResponse"][] | components["schemas"]["EdgeKindStatResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crosswalk_graph_api_v1_systems__source__crosswalk__target__graph_get: {
        parameters: {
            query?: {
                /** @description Max edges to return */
                limit?: number;
                /** @description Filter to edges within this section code */
                section?: string | null;
            };
            header?: never;
            path: {
                source: string;
                target: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrosswalkGraphResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crosswalk_sections_api_v1_systems__source__crosswalk__target__sections_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source: string;
                target: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrosswalkSectionsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_countries_api_v1_countries_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_countries_stats_api_v1_countries_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_country_profile_api_v1_countries__country_code__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                country_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    audit_provenance_api_v1_audit_provenance_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditProvenanceResponse"];
                };
            };
        };
    };
    classify_business_api_v1_classify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClassifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassifyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    classify_demo_api_v1_classify_demo_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                dev_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClassifyDemoRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassifyDemoResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_contact_api_v1_contact_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContactRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mcp_http_info_mcp_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    mcp_http_bridge_mcp_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    developers_signup_api_v1_developers_signup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignupResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    auth_magic_callback_api_v1_auth_magic_callback_get: {
        parameters: {
            query: {
                t: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_keys_api_v1_developers_keys_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                dev_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KeyMetadata"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_key_api_v1_developers_keys_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                dev_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateKeyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KeyCreatedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_key_api_v1_developers_keys__key_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key_id: string;
            };
            cookie?: {
                dev_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    checkout_endpoint_api_v1_billing_checkout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckoutRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckoutResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    portal_endpoint_api_v1_billing_portal_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortalResponse"];
                };
            };
        };
    };
    state_endpoint_api_v1_billing_state_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BillingStateResponse"];
                };
            };
        };
    };
    list_wiki_pages_api_v1_wiki_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WikiPageSummary"][];
                };
            };
        };
    };
    get_wiki_page_api_v1_wiki__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WikiPageDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_api_v1_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    version_api_v1_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    sentry_test_api_v1__internal_sentry_test_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    robots_txt_robots_txt_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    llms_txt_llms_txt_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    llms_full_txt_llms_full_txt_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
}
